import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './header'
import { Providers } from "./theme-provider"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // 
    <html lang="en">
      <head></head>
      <body className={`bg-[#FCFCFC] dark:bg-black ${inter.className}`}>
        <Providers>
        {/* <div className='text-[#0E1B18] dark:bg-[#0E1B18] dark:text-white'> */}
        <Header/>
        {children}
        {/* </div> */}
        </Providers>
      </body>
    </html>
    //  
  )
}
